from enum import Enum

class StoryError(Enum):
    GET_LATEST_CHAPTER = "ERROR_GET_LATEST_CHAPTER"
    SEND_DISCORD_GENERAL = "ERROR_SEND_DISCORD_GENERAL"
    SEND_DISCORD_PER_STORY = "ERROR_SEND_DISCORD_PER_STORY"